# Generated by Django 4.2.20 on 2025-04-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groupedintent_intent_is_grouped_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='groupedintent',
            name='interaction_events',
            field=models.JSONField(default=list),
        ),
    ]
