# Generated by Django 4.2.20 on 2025-04-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_item_groupedintent_interaction_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupedintent',
            name='intent_texts',
            field=models.JSONField(default=list),
        ),
    ]
