# Generated by Django 4.2.20 on 2025-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_groupedintent_intent_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36, unique=True)),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
